### ISSUE TITLE
Connecting

### ISSUE THREAD

**Issue by crshnbrn66** [sergeytunnik/HandyCrmPS#1]
Suggest that you add some detail on how you connect to the CRM instance. something like this: 

$connstring = 'Url=http://crm.yourdomain.com/idontcare; Domain=SomeDomain; Username=adminuser; Password=aStrongPassword;'

get-crmconnection -ConnectionString $connstring

**Comment by crshnbrn66** [comment]
Also is there a Get-crmworkflow and I'm missing it?

**Comment by sergeytunnik** [comment]
Indeed this project lucks documentation. Going to add it using platyPS in the nearest future.

Yes, there is no Get-CRMWrofklow command. Need to think which parameters and default filters to use for this cmdlet so it will be easy and straightforward to use. Cause there are categories: workflow, dialog, business rule, action, business process flow. And type: definition, activation, template. Also there may be several workflows with the same name.
